DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS BOX;

CREATE TABLE BOX
(id INTEGER PRIMARY KEY,
 contained_in INTEGER
);

CREATE TABLE ITEM
(id INTEGER PRIMARY KEY,
 contained_in INTEGER REFERENCES BOX(id),
 color VARCHAR(100)
);